version: "3.7"

services:

  nginx:
    image: nginx:1.19.5
    ports:
      - 80:80
    networks:
      - ha2_network
    volumes:
      - /home/deu05230/nginx.conf:/etc/nginx/nginx.conf
      - ha2_static:/data/static/
      - ha2_media:/data/media/


  django:
    image: ha2_django:5
    networks:
      - ha2_network
    volumes:
      - ha2_static:/home/GSWEB2/staticfiles/
      - ha2_media:/home/GSWEB2/media/
    secrets:
      - DJANGO_SECRET_KEY
      - MARIADB_USER
      - MARIADB_PASSWORD

  mariadb:
    image: mariadb:10.5
    networks:
      - ha2_network
    volumes:
      - ha2_mariadb:/var/lib/mysql
    secrets:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_USER
      - MARIADB_PASSWORD
    environment:
      MARIADB_ROOT_PASSWORD: password1234
      MARIADB_DATABASE_FILE: /run/secrets/MARIADB_USER
      MARIADB_USER_FILE: /run/secrets/MARIADB_PASSWORD
      MARIADB_PASSWORD_FILE: /run/secrets/MARIADB_ROOT_PASSWORD

networks:
  ha2_network:


volumes:
  ha2_static:
  ha2_media:
  ha2_mariadb:

secrets:
  DJANGO_SECRET_KEY:
    external: true
  MARIADB_ROOT_PASSWORD:
    external: true
  MARIADB_USER:
    external: true
  MARIADB_PASSWORD:
    external: true